planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
  ESTkConfigDefault:
    type: geometric::EST
  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
  KPIECEkConfigDefault:
    type: geometric::KPIECE
  RRTkConfigDefault:
    type: geometric::RRT
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
  RRTstarkConfigDefault:
    type: geometric::RRTstar
  RRTstarAnySolution:
    type: geometric::RRTstar
    optimization_objective: PathLengthOptimizationObjectiveAnySolution
  TRRTkConfigDefault:
    type: geometric::TRRT
  PRMkConfigDefault:
    type: geometric::PRM
  PRMAnySolution:
    type: geometric::PRM
    optimization_objective: PathLengthOptimizationObjectiveAnySolution
  PRMstarkConfigDefault:
    type: geometric::PRMstar
  LazyPRMkConfigDefault:
    type: geometryc::LazyPRM
  FMTAnySolution:
    type: geometric::FMT
    optimization_objective: PathLengthOptimizationObjectiveAnySolution
  BITstarkConfigDefault:
    type: geometric::BITstar
  BITstarAnySolution:
    type: geometric::BITstar
    optimization_objective: PathLengthOptimizationObjectiveAnySolution
arm:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - BITstarkConfigDefault
    - BITstarAnySolution
    - LazyPRMkConfigDefault
    - PRMAnySolution
    - FMTAnySolution
    - RRTstarAnySolution
  longest_valid_segment_fraction: 0.005
